name: 'Deploy Docker Image to Heroku App'
author: 'Jean Carlos Taveras, Cain Watson'
description: 'A simple action to build, push and deploy a Docker Image to your Heroku app.'
inputs:
  email:
    description: 'Email Linked to your Heroku Account'
    required: true
  api_key:
    description: 'Your Heroku API Key'
    required: true
  app_name:
    description: 'Your Heroku App Name'
    required: true
  dockerfile_path:
    description: 'Dockerfile path'
    required: false
  push_options:
    description: 'Optional container:push parameters'
    required: false
branding:
  icon: package
  color: purple
runs:
  using: 'node12'
  main: 'dist/index.js'
